server:
  port: 9090
  error:
    include-message: always

spring:
  application:
    name: labxpert
  datasource:
    url: jdbc:postgresql://localhost:5332/labxpert
    username: postgres
    password: postgres
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.simplon.labxpert: DEBUG
    org.hibernate.SQL: ERROR
  file:
    name: logs/labxpert.log